# Токен дискорд бота
token: "MTIxMDU3MTc3MjY1NTgzNzIyNg.GYOSAV.22ex6khM6MgLVOFTvuSkupeSkFy0PqXs2NQJGE"

# Айди вашего сервера
guildId: "1197957820562296892"

# Команда /suggest вызывает окно в котором есть 2 поля для заполнения, после чего они собираются и отправляются в отдельный чат
suggest:
  # Чат в который будут отправлятся предложения
  suggestChannelId: ""

# Заявки от игроков, используйте команду /resume, чтобы вызвать сообщение с кнопкой по нажатию которой откроется меню с вопросами. После их заполенения заявка отправляется в чат где её уже рос сматривает администрация. В зависимости от решения принять/отказать отправится оповещение
applications:
  # Включены ли заявки на сервере
  applicationsEnable: true

  # Чат куда будут отправляться заявки на рос смотрение
  channelId: ""

  # Каналы оповещения
  acceptChannelId: ""
  rejectChannelId: ""

  # Менять ли ник игроку которого заявку приняли, на тот что он указал в заявке
  changeNickname: false

  # Роли, что выдаются игроку которого заявку приняли
  addAcceptRolesIds:
    - ""
  # Роли, что отнимаются у игрока которого заявку приняли
  removeAcceptRolesIds:
    - ""

  # Роли, что выдаются игроку которого заявку отказали
  addRejectRolesIds:
    - ""
  # Роли, что отнимаются у игрока которого заявку отказали
  removeRejectRolesIds:
    - ""