# ВАЖНО
#
# Чтобы настроить роли вам нужно зайти на ваш сервер в дискорд по и по пути "Настройки Сервера/Интеграция/Ваш бот" настроить все что пожелаете
#
#


# Токен дискорд бота
token: ""

# ВАЖНО
# Айди вашего сервера
guildId: ""

# Команда /suggest вызывает окно в котором есть 2 поля для заполнения, после чего они собираются и отправляются в отдельный чат
suggests:
  # Чат в который будут отправлятся предложения
  suggestChannelId: ""

  # Роль для оповещения о новом предложении
  notificationRoleId: ""


# Заявки от игроков, используйте команду /resume, чтобы вызвать сообщение с кнопкой по нажатию которой откроется меню с вопросами. После их заполенения заявка отправляется в чат где её уже рос сматривает администрация. В зависимости от решения принять/отказать отправится оповещение
applications:
  # Роль для оповещения о новой заявке
  notificationRoleId: ""

  # Включены ли заявки на сервере
  applicationsEnable: true

  # Чат куда будут отправляться заявки на рос смотрение
  channelId: ""

  # Каналы оповещения
  acceptChannelId: ""
  rejectChannelId: ""

  # Менять ли ник игроку которого заявку приняли, на тот что он указал в заявке
  changeNickname: false

  # Роли, что выдаются игроку которого заявку приняли
  addAcceptRolesIds:
    - ""
  # Роли, что отнимаются у игрока которого заявку приняли
  removeAcceptRolesIds:
    - ""

  # Роли, что выдаются игроку которого заявку отказали
  addRejectRolesIds:
    - ""
  # Роли, что отнимаются у игрока которого заявку отказали
  removeRejectRolesIds:
    - ""