name: LDBot
version: '${project.version}'
main: org.ling.ldbot.main.LDBot
api-version: '1.20'

commands:
  ldbot:
    description: "general command"
    permission: "ldbot.*"
    aliases: []
    children:
      ldbot.reload: true

permissions:
  ldbot.reload:
    default: op